table '_Key Measures'
	lineageTag: 582e4f05-1c3a-4323-a562-5cc70ef875a8

	measure 'Customers - All' = DISTINCTCOUNT(dCustomer[CustomerKey])
		formatString: 0
		displayFolder: _Customers
		lineageTag: 99f69240-9eef-4cc7-ba1b-c72a3f793e74

	measure 'Customers - Current' = DISTINCTCOUNT(fSalesDetails[CustomerKey])
		formatString: 0
		displayFolder: _Customers
		lineageTag: fae7f243-3106-4fb4-bbfc-0506672671ce

	measure 'Gross Sales' = SUMX(fSalesDetails, fSalesDetails[OrderQuantity] * fSalesDetails[UnitPrice])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: be8ef380-b6f8-43d9-8ccd-cec2d2073230

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Gross Sales Last 12M' =
			
			CALCULATE(
			    [Gross Sales],
			    DATESINPERIOD(
			        fSalesDetails[OrderDate],
			        MAX(fSalesDetails[OrderDate]),
			        -12,
			        MONTH
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 046ced6a-f37d-426f-ac81-01b5b31d77ac

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Last Purchase' = MAX(fSalesDetails[OrderDate])
		formatString: d/m/yyyy
		lineageTag: f1afcfe6-4d0e-4754-a63b-4aa575abd4ae

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Sales Orders Last 12M' =
			
			VAR vSalesOrders =  DISTINCTCOUNT(fSalesDetails[SalesOrderNumber])
			RETURN
			CALCULATE(
			    vSalesOrders,
			    DATESINPERIOD(
			        fSalesDetails[OrderDate],
			        MAX(fSalesDetails[OrderDate]),
			        -12,
			        MONTH
			    )
			)
		formatString: 0
		lineageTag: 82f9d227-4827-475b-8959-2fb1beb456e1

	measure 'Customers - Recurrent (PY)' = ```
			
			VAR vPreviousY = 
			CALCULATETABLE(
			    VALUES(fSalesDetails[CustomerKey]),
			    PREVIOUSYEAR(dCalendar[DateId])
			)
			VAR vThisY = VALUES(fSalesDetails[CustomerKey])
			
			VAR vBothY = INTERSECT(vPreviousY,vThisY)
			
			RETURN
			COUNTROWS(vBothY)
			```
		formatString: 0
		displayFolder: _Customers
		lineageTag: 43539841-e991-438b-a881-4b4f1367c744

	measure 'Customers - Recurrent%' =
			
			divide([Customers - Recurrent (PY)],[Customers - All])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Customers
		lineageTag: 093411f7-710b-4874-b010-c107d632001c

	measure 'Customers - Without Sales' =
			
			VAR vAll  = VALUES(dCustomer[CustomerKey])
			VAR vCurrent = VALUES(fSalesDetails[CustomerKey])
			
			VAR vExcept = EXCEPT(vAll,vCurrent)
			RETURN
			COUNTROWS(vExcept)
		formatString: 0
		displayFolder: _Customers
		lineageTag: 8bfdf691-d473-4e8a-a324-7d6932250e10

	measure 'Customers - Without Sales%' = DIVIDE([Customers - Without Sales],[Customers - All])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Customers
		lineageTag: 2e4b0424-cafd-4d39-bb1b-c27e48f27be8

	measure 'Customers - New' =
			
			VAR vCurrent = VALUES(fSalesDetails[CustomerKey])
			VAR vOld  =
			CALCULATETABLE(
			    VALUES(fSalesDetails[CustomerKey]),
			    FILTER(
			        ALL(dCalendar),
			        dCalendar[DateId] < MIN(dCalendar[DateId])
			    )
			)
			VAR vExcept = EXCEPT(vCurrent,vOld)
			RETURN
			COUNTROWS(vExcept)
		formatString: 0
		displayFolder: _Customers
		lineageTag: 6e065398-3ff8-4cb6-a526-aa4cff22d943

	measure 'Customers - New%' = DIVIDE([Customers - New],[Customers - All])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Customers
		lineageTag: 0e0ac276-44b2-4219-91a0-40d652578700

	measure 'Gross Sales CY' =
			
			VAR AnoAtual = SELECTEDVALUE(dCalendar[Year])
			RETURN
			CALCULATE([Gross Sales],dCalendar[Year] = AnoAtual)
		lineageTag: cba9380a-1087-46df-b70d-5ec98781c207

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Sales Last Year' = CALCULATE([Gross Sales], SAMEPERIODLASTYEAR(dCalendar[DateId]))
		lineageTag: 5f2db99b-af9c-4593-82c0-36b128a0a97b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM % Gross Sales' =
			
			VAR vGrossSalesPM= CALCULATE([Gross Sales],DATEADD(dCalendar[DateId],-1,MONTH))
			RETURN
			DIVIDE([Gross Sales]-vGrossSalesPM,[Gross Sales])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e1a133a6-f78b-4c24-83e1-d4265acb1259

	measure 'YoY% Gross Sales' =
			
			VAR vGrossSalesLY = CALCULATE([Gross Sales],SAMEPERIODLASTYEAR(dCalendar[DateId]))
			RETURN
			DIVIDE([Gross Sales]-vGrossSalesLY,[Gross Sales])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3dc02118-6aff-4269-954c-7e395b2b5c0a

	measure 'Gross Sales 2014' = ```
			
			VAR vGrossSales2013 = CALCULATE([Gross Sales],dCalendar[Year] = 2013)
			VAR vGrossSales2012 = CALCULATE([Gross Sales],dCalendar[Year] = 2012)
			Return
			   IF(
			    MAX(dCalendar[MonthName]) = "May",vGrossSales2013*2,
			    IF(
			    MAX(dCalendar[MonthName]) = "December",(vGrossSales2012*1.1)*1.1,
			    vGrossSales2013*1.1))
			 
			```
		isHidden
		lineageTag: 87a5ac28-8415-4bf8-86a2-0b1d31c5c0ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Sales 2014 v2' = ```
			
			VAR vGrossSales2013 = CALCULATE([Gross Sales],dCalendar[Year] = 2013)
			VAR vGrossSales2012 = CALCULATE([Gross Sales],dCalendar[Year] = 2012)
			Return
			    SUMX(
			        CALCULATETABLE(VALUES(dCalendar[YearMonthNumber]), dCalendar[Year] = 2013),
			        [Gross Sales] * IF(dCalendar[YearMonthNumber] == 201305, 2, 1.1)
			    )
			 
			```
		isHidden
		lineageTag: c666e7be-ef39-4c53-b0d5-fcbcd1861105

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Sales 2014 v3' =
			
			VAR vGrossSales2013 = CALCULATE([Gross Sales],dCalendar[Year] = 2013)
			VAR vGrossSales2012 = CALCULATE([Gross Sales],dCalendar[Year] = 2012)
			Return
			    SUMX(
			        CALCULATETABLE(VALUES(dCalendar[YearMonthNumber]), dCalendar[Year] = 2013),
			        IF(dCalendar[YearMonthNumber] == 201312,CALCULATE([Gross Sales],dCalendar[YearMonthNumber] == 201212) *1.21,[Gross Sales] * IF(dCalendar[YearMonthNumber] == 201305, 2, 1.1))
			    )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 70b86d87-3b51-40aa-bb51-575039b2ecda

	measure 'Gross Sales ACC' =
			CALCULATE(
			    [Gross Sales],
			    DATESBETWEEN(
			        dCalendar[DateId],
			        BLANK(),
			        MAX(dCalendar[DateId])
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 19cbe21d-3f0b-46f6-8d6c-7407067f855f

	measure 'Rank Returns' =
			IF(
			    HASONEVALUE(dProduct[ProductName]),
			    RANKX(ALL(dProduct[ProductName]),[Returns]))
		formatString: 0
		lineageTag: beb02f4f-1d59-465e-9127-c89472f49c73

	measure 'Accumulated Returns' = CALCULATE([Returns],TOPN([Rank Returns],ALL(dProduct[ProductName]),[Returns],DESC))
		lineageTag: e3d2fea9-d508-4de0-9c9b-4dc3f6a936a2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accumulated Returns %' = ```
			DIVIDE([Accumulated Returns],CALCULATE([Returns],ALL(dProduct[ProductName])),0) 
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d58c97f1-6a0d-455c-93ba-ca42cde46ac5

	measure 'Gross Sales by RFM' = ```
			
			VAR vRmin = MIN(auxClassRFM[RMin])
			VAR vRmax = MAX(auxClassRFM[RMax])
			VAR vFMmin = MIN(auxClassRFM[FMMin])
			VAR vFMmax = MAX(auxClassRFM[FMMax])
			VAR vgross = 
			CALCULATE(
			    [Gross Sales Last 12M],
			    FILTER(
			        VALUES(dCustomer[Customer]),
			        [RFM - R] > vRmin && [RFM - R] <= vRmax
			        &&
			        [RFM - FM] > vFMmin && [RFM - FM] <= vFMmax
			    )
			)
			RETURN
			vgross
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: bc553dfe-422c-4883-9251-a981f76fa86d

	measure 'Last Puchase by RFM' = ```
			
			VAR vRmin = MIN(auxClassRFM[RMin])
			VAR vRmax = MAX(auxClassRFM[RMax])
			VAR vFMmin = MIN(auxClassRFM[FMMin])
			VAR vFMmax = MAX(auxClassRFM[FMMax])
			VAR vlast = 
			CALCULATE(
			    [Last Purchase],
			    FILTER(
			        VALUES(dCustomer[Customer]),
			        [RFM - R] > vRmin && [RFM - R] <= vRmax
			        &&
			        [RFM - FM] > vFMmin && [RFM - FM] <= vFMmax
			    )
			)
			RETURN
			vlast
			```
		formatString: dd/mm/yy
		lineageTag: dd569374-1184-46aa-a62d-55e7d0a38d6f

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Sales Order by RFM' = ```
			
			VAR vRmin = MIN(auxClassRFM[RMin])
			VAR vRmax = MAX(auxClassRFM[RMax])
			VAR vFMmin = MIN(auxClassRFM[FMMin])
			VAR vFMmax = MAX(auxClassRFM[FMMax])
			VAR vorder = 
			CALCULATE(
			    [Sales Orders Last 12M],
			    FILTER(
			        VALUES(dCustomer[Customer]),
			        [RFM - R] > vRmin && [RFM - R] <= vRmax
			        &&
			        [RFM - FM] > vFMmin && [RFM - FM] <= vFMmax
			    )
			)
			RETURN
			vorder
			```
		formatString: 0
		lineageTag: 6925209e-095b-46eb-81f0-8e8102f03d97

	measure 'Gross Sales 2013' =
			
			VAR vbudgetdec2013 =CALCULATE([Gross Sales],dCalendar[YearMonthNumber]=201212)*1.1
			Return
			 SUMX(
			        CALCULATETABLE(VALUES(dCalendar[YearMonthNumber]), dCalendar[Year] = 2013),
			        IF(dCalendar[YearMonthNumber] == 201312,vbudgetdec2013,
			        CALCULATE([Gross Sales],dCalendar[Year]=2013
			
			)))
		lineageTag: 52400ee7-f8bb-42df-8c45-7ec3006c3078

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY% Gross Sales 2014' =
			
			VAR vGrossSalesLY = [Gross Sales 2013]
			RETURN
			DIVIDE([Gross Sales 2014 v3]-vGrossSalesLY,[Gross Sales 2014 v3])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 480c33c8-cc06-4950-9a6c-a3f9008826f6

	measure UnitP = AVERAGE(fSalesDetails[UnitPrice])
		displayFolder: _Product Classification Matrix
		lineageTag: 660a13f3-b6b6-46a4-9b94-dea7b46c101f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UnitC = AVERAGE(fSalesDetails[Unit Cost])
		displayFolder: _Product Classification Matrix
		lineageTag: 87ac78c3-429c-415b-b48b-537b668c0d80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unit Gross Margin Ranking' = ```
			
			VAR vRank = 
			RANKX(
			    ALL(
			        dProduct[ProductName],
			        dProduct[SubcategoryName],
			        dProduct[CategoryName]
			    ),
			    [Unit Gross Margin]
			)
			RETURN
			IF(
			    ISINSCOPE(dProduct[ProductName]),
			    vRank,
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: _Product Classification Matrix
		lineageTag: 88ca2f59-60b8-4bd2-90d1-168b23e08b3e

	measure 'Unit Gross Margin' =
			
			[UnitP] - [UnitC]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _Product Classification Matrix
		lineageTag: 1491e8bb-5894-4c95-9d76-9d2d9b1ae323

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Quantity Ranking' = ```
			
			VAR vRank = 
			RANKX(
			    ALL(
			        dProduct[ProductName],
			        dProduct[SubcategoryName],
			        dProduct[CategoryName]
			    ),
			    [Quantity]
			)
			RETURN
			IF(
			    ISINSCOPE(dProduct[ProductName]),
			    vRank,
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: _Product Classification Matrix
		lineageTag: aad0257f-ca6e-4bc5-81fb-b14c529b1671

	measure Quantity = SUM(fSalesDetails[OrderQuantity])
		formatString: #,0
		displayFolder: _Product Classification Matrix
		lineageTag: 7e73000a-eee5-4764-8de7-8f126c8b5363

	measure 'Quadrants Product Count' =
			
			CALCULATE(
			    DISTINCTCOUNT(dProduct[ProductName]),
			    FILTER(
			        VALUES(dProduct[ProductName]),
			        [1/Quantity Ranking] > MIN(auxProductMatrix[xLow]) &&
			        [1/Quantity Ranking] <= MAX(auxProductMatrix[xHigh]) &&
			        [1/Unit Gross Margin Ranking] > MIN(auxProductMatrix[yLow]) &&
			        [1/Unit Gross Margin Ranking] <= MAX(auxProductMatrix[yHigh])&&
			        NOT(ISBLANK([Gross Sales])
			    )
			))
		displayFolder: _Product Classification Matrix
		lineageTag: 8e188641-61bc-4a57-8c16-1c3b95430aaa

	measure 'Quadrants Gross Sales' =
			
			CALCULATE(
			    [Gross Sales],
			    FILTER(
			        VALUES(dProduct[ProductName]),
			        [1/Quantity Ranking] > MIN(auxProductMatrix[xLow]) &&
			        [1/Quantity Ranking] <= MAX(auxProductMatrix[xHigh]) &&
			        [1/Unit Gross Margin Ranking] > MIN(auxProductMatrix[yLow]) &&
			        [1/Unit Gross Margin Ranking] <= MAX(auxProductMatrix[yHigh])
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _Product Classification Matrix
		lineageTag: a92fe86c-f0d2-4e3b-979d-554e8e5f3c60

	measure Medida
		displayFolder: _Product Classification Matrix
		lineageTag: 3b0ca624-adbc-464f-98a2-bbafb1e6dc80

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure '1/Unit Gross Margin Ranking' = DIVIDE(1,[Unit Gross Margin Ranking])
		displayFolder: _Product Classification Matrix
		lineageTag: 61316f13-fba1-4f06-a8b7-14a761673b56

	measure '1/Quantity Ranking' = DIVIDE(1,[Quantity Ranking])
		displayFolder: _Product Classification Matrix
		lineageTag: e544d045-4346-46a5-aea8-4537759ae0d2

	measure 'Av. by Customer in Total' =
			
			AVERAGEX(
			    ALL(dCustomer),
			    [Gross Sales]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: _Customers
		lineageTag: c14a9966-19dc-470b-9632-3578d1766ae3

	measure 'Gross Sales 1' = SUMX(fSalesDetails, fSalesDetails[OrderQuantity] * fSalesDetails[UnitPrice])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: _Customers
		lineageTag: c7bd4d37-5536-4add-855d-5307e5165f13

	measure 'Gross Sales for "Bad" Customers' = ```
			
			    CALCULATE(
			    [Gross Sales],
			    FILTER(
			        DCustomer,
			        [Gross Sales] <= [Av. by Customer in Total])
			)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: _Customers
		lineageTag: 419d3d33-397a-462b-b1f0-d46f3c591811

	measure '% HA' = ```
			
			VAR vMesAnterior = 
			CALCULATE(
			    [Total Amount Actual],
			    PREVIOUSMONTH(dCalendar[Dateid])
			)
			RETURN
			DIVIDE([Total Amount Actual] - vMesAnterior, ABS(vMesAnterior))
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Income Statement
		lineageTag: 8dc76c77-8cf9-4f15-b781-84612b13464b

	measure '% VA' = ```
			
			var vallgrosssales = 
			CALCULATE(
			    [Total Amount Actual],
			    dAccountHeader[AccountHeaderKey] = 3,
			    ALL(dAccount)
			)
			return
			divide([Total Amount Actual], vallgrosssales)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Income Statement
		lineageTag: d2f05498-4c45-4b10-bc9a-96a1f7fce801

	measure 'Budget Deviation' = [Total Amount Actual] - [Total Amount Budget]
		displayFolder: _Income Statement
		lineageTag: 2444d0b8-0673-4076-8325-7252a4b2ce0d

	measure 'Budget Deviation %' = DIVIDE([Budget Deviation],ABS([Total Amount Budget]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Income Statement
		lineageTag: 907cd352-e446-48f5-b145-0a1edefdc911

	measure 'Subtotal Amount' =
			
			VAR SEQMAX = MAX(dAccountHeader[AccountHeaderKey])
			RETURN
			    CALCULATE([Total Amount],
			    FILTER(ALL(dAccountHeader), dAccountHeader[AccountHeaderKey] <= SEQMAX)
			    )
		displayFolder: _Income Statement
		lineageTag: f73ed2bd-b759-4a05-9539-2a64d8020533

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Subtotal Amouth' =
			
			VAR SEQMAX = MAX(dAccountHeader[AccountHeaderKey])
			RETURN
			    CALCULATE([Total Amount],
			    FILTER(ALL(dAccountHeader), dAccountHeader[AccountHeaderKey] <= SEQMAX)
			    )
		displayFolder: _Income Statement
		lineageTag: 617b7585-f834-47e3-bf31-862b114eb53c

	measure 'Total Amount' = ```
			CALCULATE(
			    SUMX(fFinance, fFinance[Amount]*RELATED(dAccount[Sign])),
			    fFinance[Scenario]="actual"
			)
			
			```
		displayFolder: _Income Statement
		lineageTag: 8bd12cfc-6a79-4dde-8ded-371a40014d32

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Amount Actual' =
			
			VAR ESCOPOCONTA = ISINSCOPE(dAccount[Account])
			VAR ESCOPOSUBCONTA = ISINSCOPE(dAccount[AccountSubheader])
			VAR MAXDETAIL = SELECTEDVALUE(dAccountHeader[Detail])
			VAR MAXDETAILSUB = SELECTEDVALUE(dAccount[SubheaderDetail])
			RETURN
			SWITCH(
			    TRUE(),
			    MAXDETAIL = FALSE && ESCOPOSUBCONTA = FALSE(), [Subtotal Amount],
			    MAXDETAIL = TRUE && MAXDETAILSUB = FALSE && ESCOPOCONTA = TRUE(), BLANK(),
			   [Total Amount]
			)
		displayFolder: _Income Statement
		lineageTag: 4fa7cfe5-d428-4708-8dbe-e6a113d3b216

	measure 'Total Amount Budget' = ```
			
			VAR CALCVALOR = CALCULATE(
			    SUMX(fFinance, fFinance[Amount]*RELATED(dAccount[Sign])),
			    fFinance[Scenario]="budget"
			)
			VAR SEQMAX = MAX(dAccountHeader[AccountHeaderKey])
			VAR CALCVALORSUB =  
			    CALCULATE(CALCULATE(
			    SUMX(fFinance, fFinance[Amount]*RELATED(dAccount[Sign])),
			    fFinance[Scenario]="budget"),
			    FILTER(ALL(dAccountHeader), dAccountHeader[AccountHeaderKey] <= SEQMAX)
			    )
			VAR ESCOPOCONTA = ISINSCOPE(dAccount[Account])
			VAR ESCOPOSUBCONTA = ISINSCOPE(dAccount[AccountSubheader])
			VAR MAXDETAIL = SELECTEDVALUE(dAccountHeader[Detail])
			VAR MAXDETAILSUB = SELECTEDVALUE(dAccount[SubheaderDetail])
			RETURN
			SWITCH(
			    TRUE(),
			    MAXDETAIL = FALSE && ESCOPOSUBCONTA = FALSE(), CALCVALORSUB,
			    MAXDETAIL = TRUE && MAXDETAILSUB = FALSE && ESCOPOCONTA = TRUE(), BLANK(),
			   CALCVALOR
			)
			```
		displayFolder: _Income Statement
		lineageTag: 8780e814-dc1c-4f55-8313-393c6e5772ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Amount Correct' = ```
			
			VAR ESCOPOCONTA = ISINSCOPE(dAccount[Account])
			VAR ESCOPOSUBCONTA = ISINSCOPE(dAccount[AccountSubheader])
			VAR MAXDETAIL = SELECTEDVALUE(dAccountHeader[Detail])
			VAR MAXDETAILSUB = SELECTEDVALUE(dAccount[SubheaderDetail])
			RETURN
			SWITCH(
			    TRUE(),
			    MAXDETAIL = FALSE && ESCOPOSUBCONTA = FALSE(), [Subtotal Amouth],
			    MAXDETAIL = TRUE && MAXDETAILSUB = FALSE && ESCOPOCONTA = TRUE(), BLANK(),
			   [Total Amount]
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: _Income Statement
		lineageTag: d12ebae5-3efa-4f30-bf6c-f40f683e127f

	measure Returns = sumx(fSalesReturns, fSalesReturns[ReturnQuantity]*fSalesReturns[UnitPrice])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3af32715-065b-4c68-9ea5-134a0d54af42

	measure 'Cost of Sales' = ```
			
			SUMX(
			    fSalesDetails,
			    fSalesDetails[OrderQuantity]*fSalesDetails[Unit Cost]
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ebdd1f23-cf25-4843-a85b-91266640e290

	measure 'Gross Margin' = [Net Sales]-[Cost of Sales]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ce9c5cb2-9231-4596-929d-5dd3668d50d8

	measure 'Products with 5% difference margin' = ```
			CALCULATE(
			    COUNT(dProduct[ProductKey]),
			    FILTER(ALL(dProduct[ProductKey]), [Difference of real margin with respect to the average of the last 3 months] < -0.05)
			)
			
			```
		formatString: 0
		displayFolder: _Products
		lineageTag: ec5e09f8-9155-4ac9-a763-be4d4008dcf1

	measure 'Product Average Sales on Subcategory' =
			
			VAR contaprodutossubcategoria = CALCULATE(
			    DISTINCTCOUNT(dProduct[ProductKey]),
			    FILTER(ALL(dProduct[ProductKey],dProduct[ProductName], dProduct[Detail]), [Gross Sales] > 0),VALUES(dProduct[SubcategoryName]))
			VAR vCalc = CALCULATE(
			    [Gross Sales],
			    FILTER(ALL(dProduct[ProductKey],dProduct[ProductName], dProduct[Detail]), [Gross Sales]>0),
			    VALUES(dProduct[SubcategoryName])
			)
			VAR DIVID = DIVIDE(vCalc,contaprodutossubcategoria)
			RETURN
			IF([Gross Sales]>0,DIVID,BLANK())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 68b8e5fd-e221-416f-a67c-3bb5d6efea63

	measure '% Product Share on Subcategory' =
			
			VAR CALC = CALCULATE(
			    [Gross Sales],
			    FILTER(VALUES(dProduct[ProductKey]),
			    [% Product Contribution on Subcategory] >= [More than Valor] &&
			    [% Product Contribution on Subcategory] <= [Less than Valor])
			    )
			RETURN
			IF(CALC > 0, [% Product Contribution on Subcategory], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6de9a5a6-15f4-4d97-9ce8-0f7468af8952

	measure '% Customers Share on Country' =
			
			VAR CALC = CALCULATE(
			    [Gross Sales],
			    FILTER(VALUES(dCustomer[CustomerKey]),
			    [% Customer Contribution on Country] >= [More than Valor] &&
			    [% Customer Contribution on Country] <= [Less than Valor])
			    )
			RETURN
			IF(CALC > 0, [% Customer Contribution on Country], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 14b586ff-7a97-457e-8952-63dc1915e9db

	measure 'Net Sales' = ```
			[Gross Sales] - [Discounts] - [Returns]
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 12a3ff91-e417-4481-891d-aae688da84f0

	measure 'Net Margin of Products with 5% difference margin' = ```
			CALCULATE(
			    [Net Margin %],
			    FILTER(dProduct, [Difference of real margin with respect to the average of the last 3 months] < -0.05)
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Products
		lineageTag: 452da6e1-e952-4ffc-a00a-3b542c0fa9c4

	measure 'Net Margin %' = ```
			DIVIDE(
			    [Net Sales]-[Cost of Sales],
			    [Net Sales])
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4fcaeec2-3a7d-4204-ae22-f98177ee00c3

	measure 'Gross Sales*' = SUMX(fSalesDetails,fSalesDetails[OrderQuantity]*(fSalesDetails[UnitPrice]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		isHidden
		lineageTag: 0affd072-9e45-488d-8e9f-134e601176e8

	measure 'Gross Margin %' =
			DIVIDE(
			    [Gross Sales]-[Cost of Sales],
			    [Gross Sales])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e70edf0d-ebce-4752-993d-4c465aac1dc7

	measure Discounts = SUM(fSalesDetails[Discount Amount])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c70ee07a-49a2-4988-bb5b-9fb251aec0b7

	measure 'Difference of real margin with respect to the average of the last 3 months' = ```
			CALCULATE(
			[Gross Margin %]-[Average Margin Last 3 Months],
			FILTER(VALUES(dProduct[ProductKey]), [Gross Margin %]>0))
			
			```
		lineageTag: 40370966-96d1-4d38-8b18-dfc5c85fa9fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customers Average Sales on Country' =
			
			VAR contaclientespais = CALCULATE(
			    DISTINCTCOUNT(dCustomer[CustomerKey]),
			    FILTER(ALL(dCustomer[CustomerKey],dCustomer[Customer],dCustomer[CityName],dCustomer[Region.1]), [Gross Sales] > 0),
			    VALUES(dCustomer[CountryName]))
			VAR vCalc = CALCULATE(
			    [Gross Sales],
			    FILTER(ALL(dCustomer[CustomerKey],dCustomer[Customer], dCustomer[Region.1],dCustomer[CityName]), [Gross Sales]>0),
			    VALUES(dCustomer[CountryName])
			)
			VAR DIVID = DIVIDE(vCalc,contaclientespais)
			RETURN
			IF([Gross Sales]>0,DIVID,BLANK())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d834cb64-55c1-4162-9cca-51437b16a6d5

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Average Margin last 3 months filtered' = ```
			CALCULATE(
			    [Average Margin Last 3 Months],
			    FILTER(dProduct, [Difference of real margin with respect to the average of the last 3 months] < -0.05)
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1b6ab784-2fd6-45d5-bb79-e583818139e0

	measure 'Average Margin Last 3 Months' =
			
			VAR vDatamaxlastmonth = CALCULATE(MAX(dCalendar[DateId]),DATEADD(dCalendar[DateId],-1,MONTH))
			VAR vDataminprevios3months = CALCULATE(MIN(dCalendar[DateId]),DATEADD(dCalendar[DateId],-3,MONTH))
			RETURN
			CALCULATE(
			    DIVIDE([Gross Margin],[Net Sales]),
			    DATESBETWEEN(dCalendar[DateId],vDataminprevios3months,vDatamaxlastmonth)
			)
		lineageTag: a8cd1ebe-4aab-4874-a603-721bf27f3996

	measure '% Returns' = DIVIDE([Returns],[Gross Sales])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 757a02df-db7b-46a7-a677-5beba72dedc7

	measure '% Customer Contribution on Country' =
			
			if(ISINSCOPE(dCustomer[CustomerKey]),
			DIVIDE([Gross Sales],[Customers Average Sales on Country])
			,BLANK())
		displayFolder: _Customers
		lineageTag: 9acdce54-76ee-4a18-bff9-e5eed3959027

	measure '% Product Contribution on Subcategory' = ```
			
			    if(ISINSCOPE(dProduct[ProductKey]),
			    DIVIDE([Gross Sales],[Product Average Sales on Subcategory])
			    ,BLANK())
			```
		displayFolder: _Products
		lineageTag: af93693f-102e-48ea-b0ef-5059161fdb7d

	measure 'Av. by Product in Total' =
			
			AVERAGEX(
			    ALL(dProduct),
			    [Gross Sales]
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _Products
		lineageTag: ddace3f1-eab2-436f-b336-f96df47c5ca6

	measure 'Gross Sales for "Bad" Products' = ```
			
			    CALCULATE(
			    [Gross Sales],
			    FILTER(VALUES(dProduct[ProductKey]),
			        [Gross Sales] <= [Av. by Product in Total])
			)
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _Products
		lineageTag: b4259caf-3c8a-4053-b3ba-77c7592204db

	measure 'Products never sales' = CALCULATE([Products without Sales],ALL(dCalendar))
		formatString: 0
		displayFolder: _Products
		lineageTag: bd12a1a1-4e11-4f23-9dbf-d3fb29bd5917

	measure 'Products without Sales' =
			
			CALCULATE(
			            COUNTROWS('dProduct'),
			            FILTER(
			                VALUES(dProduct[ProductKey]),
			                       NOT([Gross Sales])
			            ))
		formatString: 0
		displayFolder: _Products
		lineageTag: 1dd58352-f6ee-4b03-be2f-e682fe4867c9

	measure 'Button Drill Class' =
			
			"Click to detail by " & SELECTEDVALUE(auxClassRFM[Class])
		displayFolder: _Customer Classification Matrix
		lineageTag: e3230e35-0a51-405e-a537-61fbbc5daa03

		annotation PBI_FormatHint = {"isText":true}

	measure 'Button Drill Month/Year' =
			
			"Click to detail by " & SELECTEDVALUE(dCalendar[Month/Year])
		displayFolder: _Customer Classification Matrix
		lineageTag: 2bafa5dd-8fb1-4bdf-b07f-d0eaca4375fe

		annotation PBI_FormatHint = {"isText":true}

	measure 'Button Drill Subcategory' =
			
			"Click to detail by " & SELECTEDVALUE(dProduct[SubcategoryName])
		displayFolder: _Customer Classification Matrix
		lineageTag: 2e7fd5da-83b1-496b-84fd-fad9a83a1951

		annotation PBI_FormatHint = {"isText":true}

	measure 'Customers Class' =
			
			VAR vClassrvm= SELECTEDVALUE(auxClassRFM[Class])
			RETURN
			SWITCH(
			    TRUE(),
			    vClassrvm = "Champions", [Champions],
			    vClassrvm = "Loyal Customers", [Loyal Customers],
			    vClassrvm = "Potential Loyalist", [Potential Loyalist],
			    vClassrvm = "New Customers", [New Customers],
			    vClassrvm = "Hibernating", [Hibernating],
			    vClassrvm = "Promising", [Promising],
			    vClassrvm = "Needing Attention", [Needing Attention],
			    vClassrvm = "About to Sleep", [About to Sleep],
			    vClassrvm = "Can't Lose Then", [Can't Lose Them],
			    vClassrvm = "At Risk", [At Risk],
			    vClassrvm = "Lost", [Lost],
			    BLANK()
			)
		formatString: 0
		displayFolder: _Customer Classification Matrix
		lineageTag: 3224e641-4204-4f9a-ac2e-0703b51ef329

	measure 'Customers RFM' = ```
			
			VAR vToday = MAX(dCalendar[DateId])
			VAR vResult = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        VAR vLast = 
			        CALCULATE(
			            MAX(fSalesDetails[OrderDate]),
			            FILTER(
			                ALL(dCalendar),
			                dCalendar[DateId] <= MAX(fSalesDetails[OrderDate])
			            )
			        )
			        RETURN
			        [Sales Orders Last 12M] >= MIN(auxFrequency[LowerT]) &&
			        [Sales Orders Last 12M] < MAX(auxFrequency[UpperT]) &&
			        DATEDIFF(vLast, vToday, DAY) >= MIN(auxRecency[LowerT]) &&
			        DATEDIFF(vLast, vToday, DAY) < MAX(auxRecency[UpperT])&&
			        [Gross Sales Last 12M] >=MIN(auxMonetary[LowerT])&&
			        [Gross Sales Last 12M] <MAX(auxMonetary[UpperT])
			    )
			)
			RETURN
			vResult
			```
		formatString: 0
		displayFolder: _Customer Classification Matrix
		lineageTag: d64bf710-91f1-4bac-a8c9-5d9de7a2944d

	measure 'DT Text Class' =
			
			"Filtered by " & SELECTEDVALUE(auxClassRFM[Class])
		displayFolder: _Customer Classification Matrix
		lineageTag: 55efc6f3-0c00-4e49-b58a-e9f16548986c

		annotation PBI_FormatHint = {"isText":true}

	measure 'DT Text Month/Year' =
			
			"Filtered by " & SELECTEDVALUE(dCalendar[Month/Year])
		displayFolder: _Customer Classification Matrix
		lineageTag: 9282df0f-d1ce-4eac-b385-89c7c5f9fc30

		annotation PBI_FormatHint = {"isText":true}

	measure 'DT Text Subcategory' =
			
			"Filtered by " & SELECTEDVALUE(dProduct[SubcategoryName])
		displayFolder: _Customer Classification Matrix
		lineageTag: 8dd51d44-dc63-4c1e-9c29-141093d65d27

		annotation PBI_FormatHint = {"isText":true}

	measure 'Frequency & Monetary Value' = ```
			
			VAR vRmin = MIN(auxClassRFM[RMin])
			VAR vRmax = MAX(auxClassRFM[RMax])
			VAR vFMmin = MIN(auxClassRFM[FMMin])
			VAR vFMmax = MAX(auxClassRFM[FMMax])
			VAR vfm = 
			CALCULATE(
			    [RFM - FM],
			    FILTER(
			        VALUES(dCustomer[Customer]),
			        [RFM - R] > vRmin && [RFM - R] <= vRmax
			        &&
			        [RFM - FM] > vFMmin && [RFM - FM] <= vFMmax
			    )
			)
			RETURN
			vfm
			```
		formatString: 0.0
		displayFolder: _Customer Classification Matrix
		lineageTag: 46caa419-531d-40d4-b39a-ed322d18fc95

	measure Recency = ```
			
			VAR vRmin = MIN(auxClassRFM[RMin])
			VAR vRmax = MAX(auxClassRFM[RMax])
			VAR vFMmin = MIN(auxClassRFM[FMMin])
			VAR vFMmax = MAX(auxClassRFM[FMMax])
			VAR vr = 
			CALCULATE(
			    [RFM - R],
			    FILTER(
			        VALUES(dCustomer[Customer]),
			        [RFM - R] > vRmin && [RFM - R] <= vRmax
			        &&
			        [RFM - FM] > vFMmin && [RFM - FM] <= vFMmax
			    )
			)
			RETURN
			vr
			```
		formatString: 0.0
		displayFolder: _Customer Classification Matrix
		lineageTag: d4c969e2-ba56-429a-98bc-0db2848bb798

	measure 'RFM - F' = ```
			
			VAR vSalesOrders =  DISTINCTCOUNT(fSalesDetails[SalesOrderNumber])
			VAR vSOLast12M =
			CALCULATE(
			    vSalesOrders,
			    DATESINPERIOD(
			        fSalesDetails[OrderDate],
			        MAX(fSalesDetails[OrderDate]),
			        -12,
			        MONTH
			    )
			)
			VAR vResult = 
			    SWITCH(
			        TRUE(),
			        vSalesOrders >= 5, 5,
			        vSalesOrders >= 4, 4,
			        vSalesOrders >= 3, 3,
			        vSalesOrders >= 2, 2,
			        vSalesOrders >= 1, 1
			    )
			
			RETURN vResult
			```
		formatString: 0
		displayFolder: _Customer Classification Matrix
		lineageTag: 52307108-f6e7-4bbf-9b17-ebd81eac9f70

	measure 'RFM - FM' = DIVIDE(([RFM - F]+[RFM - M]),2)
		displayFolder: _Customer Classification Matrix
		lineageTag: f93fb315-af29-40a5-8c5b-ff69e91ce6cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RFM - M' = ```
			
			VAR vGrossSales = SUMX(fSalesDetails, fSalesDetails[OrderQuantity] * fSalesDetails[UnitPrice])
			VAR vQty = 
			CALCULATE(
			    vGrossSales,
			    DATESINPERIOD(
			        fSalesDetails[OrderDate],
			        MAX(fSalesDetails[OrderDate]),
			        -12,
			        MONTH
			    )
			)
			VAR vResult = 
			    SWITCH(
			        TRUE(),
			        vQty >= 300000, 5,
			        vQty >= 200000, 4,
			        vQty >= 100000, 3,
			        vQty >= 10000, 2,
			        vQty > 0, 1
			    )
			
			RETURN vResult
			```
		formatString: 0
		displayFolder: _Customer Classification Matrix
		lineageTag: 156b40f1-2667-4353-84e5-f0e840e009a0

	measure 'RFM - R' = ```
			
			VAR vLastPurchase = MAX(fSalesDetails[OrderDate])
			VAR vMaxDate = MAX(dCalendar[DateId])
			VAR vDifDate = DATEDIFF(vLastPurchase, vMaxDate, DAY)
			VAR vResult = 
			    SWITCH(
			        TRUE(),
			        vDifDate >  360, 1,
			        vDifDate > 270 && vDifDate <= 360, 2,
			        vDifDate > 180 && vDifDate <= 270, 3,
			        vDifDate > 90 && vDifDate <= 180, 4,
			        vDifDate > 0 && vDifDate <= 90, 5,
			        BLANK()
			    )
			
			RETURN vResult
			```
		formatString: 0
		displayFolder: _Customer Classification Matrix
		lineageTag: ea0858c4-aee6-46fc-9112-474a9a55dac4

	measure 'About to Sleep' = ```
			
			VAR vResult = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>2&&[RFM - R]<=3&&[RFM - FM]>0&&[RFM - FM]<=2
			    )
			)
			RETURN
			vResult+0
			```
		displayFolder: _Customer Classes
		lineageTag: 84ea2f97-edf0-4bfd-86eb-80b19dd1c8d8

	measure 'About to Sleep%' = DIVIDE([About to Sleep],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: f4668f6e-f2eb-4a39-9baa-4ab0671550a9

	measure 'At Risk' = ```
			
			VAR vAtRiskCantLose = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>0&&[RFM - R]<=2&&[RFM - FM]>2&&[RFM - FM]<=5
			    )
			)
			VAR vResult = vAtRiskCantLose-[Can't Lose Them]
			RETURN
			vResult + 0
			```
		displayFolder: _Customer Classes
		lineageTag: d01a9bc5-7c8d-4ff0-933e-6c7197cb7aad

	measure 'At Risk%' = DIVIDE([At Risk],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: da3297a4-16e4-42fa-b626-e995ef1eb399

	measure 'Can''t Lose Them' = ```
			
			VAR vResult = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>0&&[RFM - R]<=1&&[RFM - FM]>4&&[RFM - FM]<=5
			    )
			)
			RETURN
			vResult+0
			```
		formatString: 0
		displayFolder: _Customer Classes
		lineageTag: 3868ced6-c239-46e5-a69b-3b1b0a5b254e

	measure 'Can''t Lose Them%' = DIVIDE([Can't Lose Them],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: 616b53f2-5c3d-48da-892a-ed3e33896959

	measure Champions = ```
			
			VAR vResult = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>4&&[RFM - R]<=999&&[RFM - FM]>4&&[RFM - FM]<=5
			    )
			)
			RETURN
			vResult+0
			```
		formatString: 0
		displayFolder: _Customer Classes
		lineageTag: 25a3f123-1c14-4e38-b1e4-8fdda242cdc4

	measure Champions% = DIVIDE([Champions],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: 4d37cb67-193b-4b1c-9a9f-8fbcc57f744c

	measure Hibernating = ```
			
			VAR vResult = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>1&&[RFM - R]<=2&&[RFM - FM]>1&&[RFM - FM]<=2
			    )
			)
			RETURN
			vResult+0
			```
		formatString: 0
		displayFolder: _Customer Classes
		lineageTag: b6e07c68-cc23-4a60-aaa6-f7834090536c

	measure Hibernating% = DIVIDE([Hibernating],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: 5509647f-9e6f-4adb-bf34-539742a5430a

	measure Lost = ```
			
			VAR vHibernatingLost = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>0&&[RFM - R]<=2&&[RFM - FM]>0&&[RFM - FM]<=2
			    )
			)
			VAR vResult = vHibernatingLost-[Hibernating]
			RETURN
			vResult + 0
			```
		formatString: 0
		displayFolder: _Customer Classes
		lineageTag: 03a15fe3-aed6-4db6-aa7d-e36bcf307fc1

	measure Lost% = DIVIDE([Lost],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: 55c66cdf-486a-42a4-949f-0b733fc7f058

	measure 'Loyal Customers' = ```
			
			VAR vLoyalCustomersChampions = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>2&&[RFM - R]<=999&&[RFM - FM]>3&&[RFM - FM]<=5
			    )
			)
			VAR vResult = vLoyalCustomersChampions-[Champions]
			RETURN
			vResult + 0
			```
		formatString: 0
		displayFolder: _Customer Classes
		lineageTag: 4cf72399-4b46-4f73-a212-9838affffc8d

	measure 'Loyal Customers%' = DIVIDE([Loyal Customers],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: f477fe0c-4413-480a-a9c0-267774b8b565

	measure 'Needing Attention' = ```
			
			VAR vResult = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>2&&[RFM - R]<=3&&[RFM - FM]>2&&[RFM - FM]<=3
			    )
			)
			RETURN
			vResult+0
			```
		formatString: 0
		displayFolder: _Customer Classes
		lineageTag: 1fcf4602-6dab-47d1-b2b3-608bdcbd25db

	measure 'Needing Attention%' = DIVIDE([Needing Attention],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: 7d8c773c-4886-46c2-aeca-1d1aeada567e

	measure 'New Customers' = ```
			
			VAR vResult = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>4&&[RFM - R]<=999&&[RFM - FM]>0&&[RFM - FM]<=1
			    )
			)
			RETURN
			vResult+0
			```
		formatString: 0
		displayFolder: _Customer Classes
		lineageTag: a625484e-f1a9-4e55-92fd-ddfd10e8065c

	measure 'New Customers%' = DIVIDE([New Customers],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: e1f96026-64ae-4567-9c64-51a9b84ff132

	measure 'Potential Loyalist' = ```
			
			VAR vResult = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>3&&[RFM - R]<=999&&[RFM - FM]>1&&[RFM - FM]<=3
			    )
			)
			RETURN
			vResult+0
			```
		formatString: 0
		displayFolder: _Customer Classes
		lineageTag: 46674254-4b26-41a5-ac16-3b1712019f4f

	measure 'Potential Loyalist%' = DIVIDE([Potential Loyalist],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: 508d4e9c-6d10-49f1-ac8d-f9c638cf6d0a

	measure Promising = ```
			
			VAR vResult = 
			CALCULATE(
			    [Customers - Current],
			    FILTER(
			        VALUES(fSalesDetails[CustomerKey]),
			        [RFM - R]>3&&[RFM - R]<=4&&[RFM - FM]>0&&[RFM - FM]<=1
			    )
			)
			RETURN
			vResult+0
			```
		formatString: 0
		displayFolder: _Customer Classes
		lineageTag: f5c1f1ee-505b-452b-8af8-997105bdc3fb

	measure Promising% = DIVIDE([Promising],[Customers - Current])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Customer Classes
		lineageTag: ea71bf7e-06a1-4c9e-ad1b-77e6cd2129ac

	measure 'Gross Sales for "Bad Products" difference' = DIVIDE(([Gross Sales for "Bad" Products]-[Av. by Product in Total]),[Av. by Product in Total])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Products
		lineageTag: 64717301-659f-4fa4-94c1-e5efb98b7110

	measure 'Gross Sales for "Bad" Customers difference' = DIVIDE(([Gross Sales for "Bad" Customers]-[Av. by Customer in Total]), [Av. by Customer in Total])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _Customers
		lineageTag: 79c89a18-880f-4231-a772-921d338cdfb3

	column Column1
		dataType: string
		isHidden
		lineageTag: 47362627-3078-450c-9876-d4e6575c8ee1
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition '_Key Measures-cd85c870-ae60-49f6-8c84-3aaa5fe6ee07' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

