table auxFrequency
	isHidden
	lineageTag: 904af59d-2d8b-4b77-baf2-96a286ed254e

	column FrequencyID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4494eaf9-c337-4294-8b76-2b0550378a9b
		summarizeBy: count
		sourceColumn: FrequencyID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Frequency
		dataType: string
		isHidden
		lineageTag: a90f882e-2c2d-4647-8bb3-dce5cddf3b16
		summarizeBy: none
		sourceColumn: Frequency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column LowerT
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 05135dde-5c96-4930-a6f4-6c0411fef920
		summarizeBy: sum
		sourceColumn: LowerT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UpperT
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c0da0d3c-12a8-4aca-bc8f-c9b039f4e33c
		summarizeBy: sum
		sourceColumn: UpperT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition auxFrequency-41f5f45c-e408-4975-b3ce-5431186ad034 = m
		mode: import
		source =
				let
				    Source = Table.FromList(
				    {
				        [ID = 1, Frequency = "F1", LowerT = 0, UpperT=1], //bad customer
				        [ID = 2, Frequency = "F2", LowerT = 1, UpperT=2],
				        [ID = 3, Frequency = "F3", LowerT = 2, UpperT=3],
				        [ID = 4, Frequency = "F4", LowerT = 3, UpperT=4],
				        [ID = 5, Frequency = "F5", LowerT = 4, UpperT=9999] // good cutomer
				
				    },
				    Record.FieldValues,
				    {"FrequencyID", "Frequency", "LowerT", "UpperT"}
				),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"FrequencyID", Int64.Type}, {"Frequency", type text}, {"LowerT", Int64.Type}, {"UpperT", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

