table 'auxLess than'
	isHidden
	lineageTag: 998e7034-e2f5-4193-9bea-7f15bdc32f81

	measure 'Less than Valor' = SELECTEDVALUE('auxLess than'[Less than])
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: fec1a8e5-6b15-426d-a15e-5c477c7f6bc8

	column 'Less than'
		isHidden
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9a859c75-3999-4b1d-a511-222e47bd8f75
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'auxLess than-863776d3-13f8-4aec-a3f4-34f9c27bf820' = calculated
		mode: import
		source = GENERATESERIES(0, 10, 0.25)

	annotation PBI_Id = 5038a5012e6b49c492378982d349e213

