table auxRecency
	isHidden
	lineageTag: 2c6680f5-10a5-4376-add7-8510b4a4f786

	column RecencyID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b253b2f3-ec48-4919-9583-740873e9e830
		summarizeBy: count
		sourceColumn: RecencyID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Recency
		dataType: string
		isHidden
		lineageTag: eda46169-d79e-44f6-81e3-7badae484ca3
		summarizeBy: none
		sourceColumn: Recency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column LowerT
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9fbac1c6-ee2b-4f07-af77-4e655758e151
		summarizeBy: sum
		sourceColumn: LowerT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UpperT
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4557979d-5870-4a38-8381-725b30da40dd
		summarizeBy: sum
		sourceColumn: UpperT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition auxRecency-3cbccedb-0a3b-41c3-af48-8d2b78ed19ab = m
		mode: import
		source =
				let
				    Source = Table.FromList(
				    {
				        [ID = 1, Recency = "R1", LowerT = 360, UpperT=9999], // bad customer
				        [ID = 2, Recency = "R2", LowerT = 270, UpperT=360],
				        [ID = 3, Recency = "R3", LowerT = 180, UpperT=270],
				        [ID = 4, Recency = "R4", LowerT = 90, UpperT=180],
				        [ID = 5, Recency = "R5", LowerT = 0, UpperT=90] // good customer
				
				    },
				    Record.FieldValues,
				    {"RecencyID", "Recency", "LowerT", "UpperT"}
				),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"RecencyID", Int64.Type}, {"Recency", type text}, {"LowerT", Int64.Type}, {"UpperT", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

