table dAccountHeader
	lineageTag: 577be596-0ec9-43f0-a9ef-18dddf70b251

	column AccountHeaderKey
		dataType: int64
		formatString: 0
		lineageTag: e1ec690f-b525-44ea-b610-2900390ead8e
		summarizeBy: none
		sourceColumn: AccountHeaderKey

		annotation SummarizationSetBy = Automatic

	column AccountHeader
		dataType: string
		lineageTag: e67c7dd7-85a2-4066-bc1a-da6bb6402559
		summarizeBy: none
		sourceColumn: AccountHeader
		sortByColumn: AccountHeaderKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Detail
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ca9f6d67-d2bb-4e93-a69e-6833442b9dbf
		summarizeBy: none
		sourceColumn: Detail

		annotation SummarizationSetBy = Automatic

	partition dAccountHeader-618a0511-03ac-48bd-a3c2-53e10290640a = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\phg\Desktop\BootCamp\Squad\DataBase.xlsx"), null, true),
				    AccountHeader_Sheet = Fonte{[Item="AccountHeader",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(AccountHeader_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"AccountHeaderKey", Int64.Type}, {"AccountHeader", type text}, {"Detail", type logical}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

