table dAccount
	lineageTag: d2740ea2-b14d-4b13-9c2c-4d44e44fd2f9

	column AccountKey
		dataType: int64
		formatString: 0
		lineageTag: cf034f69-7b03-4d10-8835-ae746f217b89
		summarizeBy: none
		sourceColumn: AccountKey

		annotation SummarizationSetBy = Automatic

	column Account
		dataType: string
		lineageTag: f3ead70e-096c-4e66-97a9-9245e350e649
		summarizeBy: none
		sourceColumn: Account
		sortByColumn: AccountKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column AccountType
		dataType: string
		lineageTag: 249ef732-87db-4e8b-8325-b8d1ad469480
		summarizeBy: none
		sourceColumn: AccountType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Sign
		dataType: int64
		formatString: 0
		lineageTag: 870cfc41-ab3a-4027-b5c2-43414d3bbb7e
		summarizeBy: sum
		sourceColumn: Sign

		annotation SummarizationSetBy = Automatic

	column AccountHeaderKey
		dataType: int64
		formatString: 0
		lineageTag: ac40cfd3-4eae-47cd-9c68-d4aca64e1b18
		summarizeBy: none
		sourceColumn: AccountHeaderKey

		annotation SummarizationSetBy = Automatic

	column AccountSubheaderKey
		dataType: int64
		formatString: 0
		lineageTag: 2b3bef84-7391-4dd2-bad5-c2513892dd81
		summarizeBy: count
		sourceColumn: AccountSubheaderKey

		annotation SummarizationSetBy = Automatic

	column AccountSubheader
		dataType: string
		lineageTag: f93824c4-b110-4c9e-8461-d939b54523ce
		summarizeBy: none
		sourceColumn: AccountSubheader
		sortByColumn: AccountSubheaderKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column SubheaderDetail
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 59871687-38b1-4a3e-8b1b-b0fb5b8e3f8a
		summarizeBy: none
		sourceColumn: SubheaderDetail

		annotation SummarizationSetBy = Automatic

	partition dAccount-f5ea57c4-86ea-48f2-889c-6f1c2f666739 = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\phg\Desktop\BootCamp\Squad\DataBase.xlsx"), null, true),
				    Account_Sheet = Fonte{[Item="Account",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Account_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"AccountKey", Int64.Type}, {"Account", type text}, {"AccountType", type text}, {"Sign", Int64.Type}, {"AccountHeaderKey", Int64.Type}, {"AccountSubheaderKey", Int64.Type}, {"AccountSubheader", type text}, {"SubheaderDetail", type logical}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

