table dDepartentGroup
	lineageTag: e153fdbf-cedc-490c-a983-f081e46b421d

	column DepartmentGroupKey
		dataType: int64
		formatString: 0
		lineageTag: f49292f1-d968-43d7-b111-4fcbb720116d
		summarizeBy: none
		sourceColumn: DepartmentGroupKey

		annotation SummarizationSetBy = Automatic

	column DepartmentGroupName
		dataType: string
		lineageTag: a51a5b6a-b402-4c0f-91c4-9c8a24da4651
		summarizeBy: none
		sourceColumn: DepartmentGroupName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition dDepartentGroup-53d41aad-fe2e-4fa7-8799-e42e67014b86 = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\phg\Desktop\BootCamp\Squad\DataBase.xlsx"), null, true),
				    DepartentGroup_Sheet = Fonte{[Item="DepartentGroup",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(DepartentGroup_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"DepartmentGroupKey", Int64.Type}, {"DepartmentGroupName", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

