table dProduct
	lineageTag: 8a04ea9a-2c00-4d12-a060-33a0f64443cb

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 422ed551-d046-46fc-944a-f449f29ec8b6
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 5c5c8c99-44ba-45c1-a43d-1fde9355c516
		summarizeBy: count
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: a268798b-376d-4333-bd84-976a8ce8fbf4
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Size
		dataType: string
		lineageTag: d9f1133a-aa34-4d11-8b9b-23c177968f9c
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Detail
		dataType: string
		lineageTag: 7b105331-b05d-4417-905f-8a340fdf17f6
		summarizeBy: none
		sourceColumn: Detail

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column SubcategoryName
		dataType: string
		lineageTag: cfb5678a-c809-440a-a3ce-07a103b24fb7
		summarizeBy: none
		sourceColumn: SubcategoryName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column CategoryName
		dataType: string
		lineageTag: c7e97131-e220-4f1b-8b04-f8f4de989fd8
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition dProduct-561cd8e2-73cf-4e6f-b24b-05ca666270b0 = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\phg\Desktop\BootCamp\Squad\DataBase.xlsx"), null, true),
				    Product_Sheet = Fonte{[Item="Product",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Product_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ProductKey", Int64.Type}, {"ProductSubcategoryKey", Int64.Type}, {"ProductName", type text}, {"Size", type text}, {"Detail", type text}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado", {"ProductSubcategoryKey"}, ProductSubcategory, {"ProductSubcategoryKey"}, "ProductSubcategory", JoinKind.LeftOuter),
				    #"ProductSubcategory Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "ProductSubcategory", {"SubcategoryName", "CategoryName"}, {"SubcategoryName", "CategoryName"})
				in
				    #"ProductSubcategory Expandido"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

