table fFinance
	lineageTag: 469c095c-a3db-4f18-b81a-d7656964d944

	column FinanceKey
		dataType: int64
		formatString: 0
		lineageTag: 42fc2a08-7213-44dd-a17c-60c871ef3a4e
		summarizeBy: count
		sourceColumn: FinanceKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7718981b-2faa-4f48-9d3f-65d0946d8aa1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrganizationKey
		dataType: int64
		formatString: 0
		lineageTag: 63414781-500b-4430-b314-a09efaca7480
		summarizeBy: none
		sourceColumn: OrganizationKey

		annotation SummarizationSetBy = Automatic

	column DepartmentGroupKey
		dataType: int64
		formatString: 0
		lineageTag: 3e665812-f2e6-4df9-a9b8-6edd75247d82
		summarizeBy: none
		sourceColumn: DepartmentGroupKey

		annotation SummarizationSetBy = Automatic

	column AccountKey
		dataType: int64
		formatString: 0
		lineageTag: c8cbfeb8-3929-454a-b391-23202426264c
		summarizeBy: none
		sourceColumn: AccountKey

		annotation SummarizationSetBy = Automatic

	column Scenario
		dataType: string
		lineageTag: 7f51182e-d789-4036-baff-735dab191edf
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Amount
		dataType: double
		lineageTag: eeee1bad-af65-4bab-aa88-5e21dcb2d881
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fFinance-7f093ec5-5a12-45fb-a677-3957c537237d = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\phg\Desktop\BootCamp\Squad\DataBase.xlsx"), null, true),
				    Finance_Sheet = Fonte{[Item="Finance",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Finance_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"FinanceKey", Int64.Type}, {"Date", type date}, {"OrganizationKey", Int64.Type}, {"DepartmentGroupKey", Int64.Type}, {"AccountKey", Int64.Type}, {"Scenario", type text}, {"Amount", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

