table fSalesDetails
	lineageTag: 833cd468-fe4f-4c03-bcd8-dc94c2c6dc16

	column SalesDetailsKey
		dataType: int64
		formatString: 0
		lineageTag: 2c8b77df-d448-4af2-8983-2f173e4cccfe
		summarizeBy: count
		sourceColumn: SalesDetailsKey

		annotation SummarizationSetBy = Automatic

	column SalesHeaderKey
		dataType: int64
		formatString: 0
		lineageTag: 9c609e22-10ad-47b2-b9ce-751fdf7d1be8
		summarizeBy: count
		sourceColumn: SalesHeaderKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: 7f8022ee-588d-41df-bbb4-610df56f5220
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 3fa13ca0-bb5c-4b52-8f73-52a6b89d5729
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 29dd4da7-1fea-488a-920e-5648b4a78c8d
		summarizeBy: count
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 2faf3273-f05e-415e-8a26-9039a1a7ddf4
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 3c71114f-8508-4541-b32b-aa5ebd31c465
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExtendedAmount
		dataType: double
		lineageTag: 2de7f49e-896d-480d-9b21-b164fb79da56
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6d8ad474-ce3e-44ff-afa7-a0b82115a7f5
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1c732405-89e9-4a57-932f-5813a7b6a9c9
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ShipDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: ca01fc2b-7108-4741-ab01-df27d6ccb4f2
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 86ae9a39-aa0b-4621-bb92-26bf83e77cf4
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column RegionKey
		dataType: int64
		formatString: 0
		lineageTag: 4a0c90d6-fa9a-4562-955e-214e286e7143
		summarizeBy: count
		sourceColumn: RegionKey

		annotation SummarizationSetBy = Automatic

	column 'Unit Cost' =
			
			VAR datamin = MIN(fSalesDetails[OrderDate])
			Return
			LOOKUPVALUE(fProductCostHistory[UnitCost],fProductCostHistory[CountryCode],RELATED(dCustomer[CountryCode]),fProductCostHistory[MonthNo],RELATED(dCalendar[Month]),fProductCostHistory[ProductKey],fSalesDetails[ProductKey],fProductCostHistory[Year],RELATED(dCalendar[Year]))
		lineageTag: 8ccef85f-f46f-4b5e-bdff-6fc63f3921bc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Discount'
		dataType: string
		lineageTag: 1fce56de-8153-4669-a3f2-244323bb5b0a
		summarizeBy: none
		sourceColumn: % Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Discount Amount' = fSalesDetails[ExtendedAmount]*fSalesDetails[% Discount]
		lineageTag: 2f5bccb4-2f37-42fc-a72c-c2b42ac1e95f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fSalesDetails-5d1e5172-9c84-4034-b42d-5521d4c73eaa = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\phg\Desktop\BootCamp\Squad\DataBase.xlsx"), null, true),
				    SalesDetails_Sheet = Fonte{[Item="SalesDetails",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(SalesDetails_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"SalesDetailsKey", Int64.Type}, {"SalesHeaderKey", Int64.Type}, {"SalesOrderNumber", type text}, {"ProductKey", Int64.Type}, {"ProductSubcategoryKey", Int64.Type}, {"OrderQuantity", Int64.Type}, {"UnitPrice", type number}, {"ExtendedAmount", type number}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado", {"SalesHeaderKey"}, fatSalesHeader, {"SalesHeaderKey"}, "fatSalesHeader", JoinKind.LeftOuter),
				    #"fatSalesHeader Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "fatSalesHeader", {"OrderDate", "DueDate", "ShipDate", "CustomerKey", "RegionKey", "% Discount"}, {"OrderDate", "DueDate", "ShipDate", "CustomerKey", "RegionKey", "% Discount"})
				in
				    #"fatSalesHeader Expandido"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

