table fSalesReturns
	lineageTag: 5d9d0a82-679a-43fc-b6e1-62c768b61148

	column ReturnKey
		dataType: int64
		formatString: 0
		lineageTag: 70855a66-6aa5-4ba1-a7d8-74383fdc6f0e
		summarizeBy: count
		sourceColumn: ReturnKey

		annotation SummarizationSetBy = Automatic

	column ReturnDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0fe9a2a4-62f8-41f4-85b3-eb48f7f576e5
		summarizeBy: none
		sourceColumn: ReturnDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b6336c96-de5f-4349-83fe-115ea9f08fb0
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SalesOrderNumber
		dataType: string
		lineageTag: e16c6f62-f989-4542-bd65-a52fe6bb45dd
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 5ed08af1-64c6-44e6-a7f3-7af8b8bb1025
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 2393df9d-beca-4509-9b2e-5b9e4a492789
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: 62bc97cf-7c80-4345-8a82-e7b34abcc0a0
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 1f8dc726-e8ba-42bb-b848-1631c2989597
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ReturnAmount
		dataType: double
		lineageTag: 1f9a6838-94b8-4bc7-b6f6-50d71c603dfb
		summarizeBy: sum
		sourceColumn: ReturnAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fSalesReturns-4509449a-818b-4e58-a2d2-d1f3c0e5bed7 = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\phg\Desktop\BootCamp\Squad\DataBase.xlsx"), null, true),
				    SalesReturns_Sheet = Fonte{[Item="SalesReturns",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(SalesReturns_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ReturnKey", Int64.Type}, {"ReturnDate", type date}, {"OrderDate", type date}, {"SalesOrderNumber", type text}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"ReturnQuantity", Int64.Type}, {"UnitPrice", type number}, {"ReturnAmount", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Exception

